- [fairness of coin](#Learning-fairness-of-coin)
- [Proportions of colors in deck](#Learning-Proportions-of-colors-in-deck)
- [a noisy parameter](#Learning-a-noisy-parameter)
- [First Success](#First-success)
- [Average lifetime](#Average-lifetime)

fairness of coin
---

In [1]:
import probpy as pp

coin = pp.bernoulli.med(probability=0.7)

prior = pp.beta.med(a=3.0, b=3.0) # 50 50 prior
likelihood = pp.bernoulli.med() # likelihood is a bernoulli

for _ in range(20):
    outcome = coin.sample()
    prior = pp.parameter_posterior(outcome, likelihood=likelihood, priors=prior)
    
    prediction = pp.predictive_posterior(likelihood=likelihood, priors=prior)
    
    print(prediction.probability)

0.42857142857142855
0.5
0.5555555555555556
0.6
0.6363636363636364
0.6666666666666666
0.6923076923076923
0.7142857142857143
0.6666666666666666
0.6875
0.6470588235294118
0.6111111111111112
0.631578947368421
0.65
0.6666666666666666
0.6818181818181818
0.6521739130434783
0.6666666666666666
0.68
0.6923076923076923


Proportions of colors in a deck
---

In [2]:
import numpy as np

card_probabilities = np.array([0.1, 0.2, 0.5, 0.2])

cards = pp.categorical.med(probabilities=card_probabilities)

prior = pp.dirichlet.med(alpha=np.ones(4) * 3)
likelihood = pp.categorical.med()

for i in range(200):
    card = cards.sample()    
    prior = pp.parameter_posterior(card, likelihood=likelihood, priors=prior)
        
    if i % 10 == 0:
        print(pp.mode(prior))

[0.22222222 0.22222222 0.33333333 0.22222222]
[0.10526316 0.15789474 0.47368421 0.26315789]
[0.10344828 0.10344828 0.62068966 0.17241379]
[0.1025641  0.07692308 0.64102564 0.17948718]
[0.08163265 0.14285714 0.6122449  0.16326531]
[0.08474576 0.18644068 0.59322034 0.13559322]
[0.08695652 0.15942029 0.5942029  0.15942029]
[0.08860759 0.15189873 0.59493671 0.16455696]
[0.08988764 0.13483146 0.57303371 0.20224719]
[0.1010101  0.14141414 0.57575758 0.18181818]
[0.09174312 0.1559633  0.55045872 0.20183486]
[0.09243697 0.15966387 0.53781513 0.21008403]
[0.08527132 0.15503876 0.54263566 0.21705426]
[0.07913669 0.15827338 0.56115108 0.20143885]
[0.08053691 0.16107383 0.55033557 0.20805369]
[0.08805031 0.1509434  0.54716981 0.21383648]
[0.08284024 0.14201183 0.55029586 0.22485207]
[0.08379888 0.13407821 0.55865922 0.22346369]
[0.08465608 0.13756614 0.56084656 0.21693122]
[0.09547739 0.14572864 0.55276382 0.20603015]


a noisy parameter
---

In [3]:
parameter = pp.normal.med(mu=5.0, sigma=10.0)

prior = pp.normal_inverse_gamma.med(mu=1.0, lam=5.0, a=4.0, b=3.0)
likelihood = pp.normal.med()

for i in range(100):
    sample = parameter.sample()
    
    prior = pp.parameter_posterior(sample, likelihood=likelihood, priors=prior)
    
    if i % 10 == 0:
        print("Mu estimate", prior.mu, "Sigma estimate", prior.b / (prior.a - 1))


Mu estimate 1.7151003400140452 Sigma estimate 3.0487221269494422
Mu estimate 4.719186419246861 Sigma estimate 12.660566439454273
Mu estimate 4.856517916465321 Sigma estimate 9.72609040202384
Mu estimate 4.575980050863169 Sigma estimate 8.840056494317865
Mu estimate 4.60594058752315 Sigma estimate 9.216512786356683
Mu estimate 4.755137324854568 Sigma estimate 10.58858928058861
Mu estimate 4.8148300575476615 Sigma estimate 12.07442370444623
Mu estimate 5.029113515736659 Sigma estimate 11.35566302684957
Mu estimate 4.95194936040825 Sigma estimate 11.103324863437127
Mu estimate 5.022270081113264 Sigma estimate 10.964479651778529


First success
---

In [4]:
first_success = pp.geometric.med(probability=0.1)

prior = pp.beta.med(a=2.0, b=2.0)
likelihood = pp.geometric.med()

for i in range(100):
    success_on = first_success.sample()
    
    prior = pp.parameter_posterior(success_on, likelihood=likelihood, priors=prior)
    
    if i % 10 == 0:
        print("First success probability", 1 / (prior.b / (prior.a - 1)))

First success probability 0.15384615384615385
First success probability 0.11214953271028039
First success probability 0.10138248847926268
First success probability 0.09090909090909091
First success probability 0.09722222222222221
First success probability 0.09471766848816028
First success probability 0.09281437125748504
First success probability 0.08823529411764705
First success probability 0.0841025641025641
First success probability 0.08417200365965234


Average lifetime
---

In [5]:
product = pp.exponential.med(lam=3.0)

prior = pp.gamma.med(a=2.0, b=2.0)
likelihood = pp.exponential.med()

for i in range(100):
    lifetime = product.sample()
    
    prior = pp.parameter_posterior(lifetime, likelihood=likelihood, priors=prior)
    
    if i % 10 == 0:
        print("Average lifetime", prior.a / prior.b)

Average lifetime 1.4101385688279506
Average lifetime 2.704367785716237
Average lifetime 3.0076349022231033
Average lifetime 3.1952833428771674
Average lifetime 2.8139807101475096
Average lifetime 3.1040329162540625
Average lifetime 3.0998648610777657
Average lifetime 3.0528721040475935
Average lifetime 3.0211689921293705
Average lifetime 3.0353196560992064
