- [fairness of coin](#Learning-fairness-of-coin)
- [Proportions of colors in deck](#Learning-Proportions-of-colors-in-deck)
- [a noisy parameter](#Learning-a-noisy-parameter)
- [First Success](#First-success)
- [Average lifetime](#Average-lifetime)

fairness of coin
---

In [4]:
import probpy as pp

coin = pp.bernoulli.med(probability=0.7)

prior = pp.beta.med(a=3.0, b=3.0) # 50 50 prior
likelihood = pp.bernoulli.med() # likelihood is a bernoulli

for _ in range(20):
    outcome = coin.sample()
    prior = pp.parameter_posterior(outcome, likelihood=likelihood, priors=prior)
    
    prediction = pp.predictive_posterior(likelihood=likelihood, priors=prior)
    
    print(prediction.probability)

0.5714285714285714
0.625
0.6666666666666666
0.7
0.6363636363636364
0.6666666666666666
0.6923076923076923
0.7142857142857143
0.6666666666666666
0.625
0.6470588235294118
0.6111111111111112
0.631578947368421
0.65
0.6666666666666666
0.6818181818181818
0.6956521739130435
0.7083333333333334
0.68
0.6923076923076923


Proportions of colors in a deck
---

In [5]:
import numpy as np

card_probabilities = np.array([0.1, 0.2, 0.5, 0.2])

cards = pp.categorical.med(probabilities=card_probabilities)

prior = pp.dirichlet.med(alpha=np.ones(4) * 3)
likelihood = pp.categorical.med()

for i in range(200):
    card = cards.sample()    
    prior = pp.parameter_posterior(card, likelihood=likelihood, priors=prior)
        
    if i % 10 == 0:
        print(pp.mode(prior))

[0.22222222 0.22222222 0.33333333 0.22222222]
[0.10526316 0.26315789 0.42105263 0.21052632]
[0.06896552 0.24137931 0.51724138 0.17241379]
[0.1025641  0.20512821 0.53846154 0.15384615]
[0.08163265 0.18367347 0.55102041 0.18367347]
[0.08474576 0.20338983 0.54237288 0.16949153]
[0.07246377 0.1884058  0.53623188 0.20289855]
[0.07594937 0.20253165 0.53164557 0.18987342]
[0.06741573 0.20224719 0.53932584 0.19101124]
[0.07070707 0.18181818 0.55555556 0.19191919]
[0.0733945  0.16513761 0.57798165 0.18348624]
[0.07563025 0.16806723 0.57983193 0.17647059]
[0.06976744 0.19379845 0.55813953 0.17829457]
[0.07194245 0.1942446  0.56834532 0.16546763]
[0.06711409 0.19463087 0.57718121 0.16107383]
[0.06918239 0.20125786 0.56603774 0.16352201]
[0.07100592 0.20118343 0.5739645  0.15384615]
[0.0726257  0.2122905  0.56424581 0.15083799]
[0.07407407 0.20634921 0.56613757 0.15343915]
[0.07035176 0.20603015 0.57286432 0.15075377]


a noisy parameter
---

In [6]:
parameter = pp.normal.med(mu=5.0, sigma=10.0)

prior = pp.normal_inverse_gamma.med(mu=1.0, lam=5.0, a=4.0, b=3.0)
likelihood = pp.normal.med()

for i in range(100):
    sample = parameter.sample()
    
    prior = pp.parameter_posterior(sample, likelihood=likelihood, priors=prior)
    
    if i % 10 == 0:
        print("Mu estimate", prior.mu, "Sigma estimate", prior.b / (prior.a - 1))


Mu estimate 2.386318978722101 Sigma estimate 9.093772760421809
Mu estimate 3.6296902556881934 Sigma estimate 11.331831769743086
Mu estimate 4.257945196802593 Sigma estimate 10.702676668995306
Mu estimate 4.170142195394556 Sigma estimate 9.336274683414032
Mu estimate 4.222702066439336 Sigma estimate 8.128175404300105
Mu estimate 4.013989848518606 Sigma estimate 8.957934301293472
Mu estimate 4.432448890147271 Sigma estimate 9.987263441272273
Mu estimate 4.587838325123863 Sigma estimate 10.729740334074755
Mu estimate 4.8004021890860855 Sigma estimate 10.485051254989292
Mu estimate 4.976307795229652 Sigma estimate 9.848078762594334


First success
---

In [7]:
first_success = pp.geometric.med(probability=0.1)

prior = pp.beta.med(a=2.0, b=2.0)
likelihood = pp.geometric.med()

for i in range(100):
    success_on = first_success.sample()
    
    prior = pp.parameter_posterior(success_on, likelihood=likelihood, priors=prior)
    
    if i % 10 == 0:
        print("First success probability", 1 / (prior.b / (prior.a - 1)))

First success probability 0.1
First success probability 0.11650485436893203
First success probability 0.10891089108910891
First success probability 0.11267605633802817
First success probability 0.1024390243902439
First success probability 0.10655737704918032
First success probability 0.10580204778156997
First success probability 0.10329985652797705
First success probability 0.0993939393939394
First success probability 0.09735449735449735


Average lifetime
---

In [8]:
product = pp.exponential.med(lam=3.0)

prior = pp.gamma.med(a=2.0, b=2.0)
likelihood = pp.exponential.med()

for i in range(100):
    lifetime = product.sample()
    
    prior = pp.parameter_posterior(lifetime, likelihood=likelihood, priors=prior)
    
    if i % 10 == 0:
        print("Average lifetime", prior.a / prior.b)

Average lifetime 1.420505536958994
Average lifetime 1.9766662443552792
Average lifetime 2.711583606641255
Average lifetime 2.947795738678642
Average lifetime 2.589790882835449
Average lifetime 2.7808185792128386
Average lifetime 2.9025000216410697
Average lifetime 2.734171932903773
Average lifetime 2.9267827670397626
Average lifetime 3.0420082845067022
