- [fairness of coin](#Learning-fairness-of-coin)
- [Proportions of colors in deck](#Learning-Proportions-of-colors-in-deck)
- [a noisy parameter](#Learning-a-noisy-parameter)
- [First Success](#First-success)
- [Average lifetime](#Average-lifetime)

fairness of coin
---

In [1]:
import probpy as pp

coin = pp.bernoulli.med(probability=0.7)

prior = pp.beta.med(a=3.0, b=3.0) # 50 50 prior
likelihood = pp.bernoulli.med() # likelihood is a bernoulli

for _ in range(20):
    outcome = coin.sample()
    prior = pp.parameter_posterior(outcome, likelihood=likelihood, prior=prior)
    
    prediction = pp.predictive_posterior(likelihood=likelihood, priors=prior)
    
    print(prediction.probability)

0.5714285714285714
0.625
0.5555555555555556
0.6
0.6363636363636364
0.6666666666666666
0.6923076923076923
0.7142857142857143
0.7333333333333333
0.75
0.7647058823529411
0.7777777777777778
0.7368421052631579
0.75
0.7619047619047619
0.7727272727272727
0.7391304347826086
0.75
0.76
0.7307692307692307


Proportions of colors in a deck
---

In [2]:
import numpy as np

card_probabilities = np.array([0.1, 0.2, 0.5, 0.2])

cards = pp.categorical.med(probabilities=card_probabilities)

prior = pp.dirichlet.med(alpha=np.ones(4) * 3)
likelihood = pp.categorical.med()

for i in range(200):
    card = cards.sample()    
    prior = pp.parameter_posterior(card, likelihood=likelihood, prior=prior)
        
    if i % 10 == 0:
        print(pp.mode(prior))

[0.22222222 0.22222222 0.22222222 0.33333333]
[0.21052632 0.15789474 0.31578947 0.31578947]
[0.17241379 0.13793103 0.48275862 0.20689655]
[0.17948718 0.12820513 0.51282051 0.17948718]
[0.18367347 0.14285714 0.51020408 0.16326531]
[0.18644068 0.15254237 0.50847458 0.15254237]
[0.17391304 0.15942029 0.44927536 0.2173913 ]
[0.15189873 0.16455696 0.46835443 0.21518987]
[0.15730337 0.14606742 0.49438202 0.20224719]
[0.16161616 0.16161616 0.49494949 0.18181818]
[0.1559633  0.1559633  0.48623853 0.20183486]
[0.14285714 0.17647059 0.48739496 0.19327731]
[0.13178295 0.17829457 0.50387597 0.18604651]
[0.1294964  0.17266187 0.50359712 0.1942446 ]
[0.12080537 0.17449664 0.51677852 0.18791946]
[0.11949686 0.16981132 0.50943396 0.20125786]
[0.13017751 0.15976331 0.5147929  0.19526627]
[0.12849162 0.15642458 0.50837989 0.20670391]
[0.13756614 0.15873016 0.49206349 0.21164021]
[0.13567839 0.16582915 0.48241206 0.2160804 ]


a noisy parameter
---

In [3]:
parameter = pp.normal.med(mu=5.0, sigma=10.0)

prior = pp.normal_inverse_gamma.med(mu=1.0, lam=5.0, a=4.0, b=3.0)
likelihood = pp.normal.med()

for i in range(100):
    sample = parameter.sample()
    
    prior = pp.parameter_posterior(sample, likelihood=likelihood, prior=prior)
    
    if i % 10 == 0:
        print("Mu estimate", prior.mu, "Sigma estimate", prior.b / (prior.a - 1))


Mu estimate 1.6305308629931308 Sigma estimate 2.5610107250865517
Mu estimate 3.852010398077393 Sigma estimate 7.8943583723476065
Mu estimate 4.705217396249322 Sigma estimate 8.837615284088804
Mu estimate 5.21389433753575 Sigma estimate 9.345947807839805
Mu estimate 5.123517158049604 Sigma estimate 8.004896029751297
Mu estimate 5.185767099434257 Sigma estimate 9.520870942640935
Mu estimate 5.081358835783046 Sigma estimate 9.10797993986148
Mu estimate 4.99859069616187 Sigma estimate 8.95660728666188
Mu estimate 5.085338186936546 Sigma estimate 8.514492339830344
Mu estimate 5.000584673870679 Sigma estimate 9.087064165836304


First success
---

In [4]:
first_success = pp.geometric.med(probability=0.1)

prior = pp.beta.med(a=2.0, b=2.0)
likelihood = pp.geometric.med()

for i in range(100):
    success_on = first_success.sample()
    
    prior = pp.parameter_posterior(success_on, likelihood=likelihood, prior=prior)
    
    if i % 10 == 0:
        print("First success probability", 1 / (prior.b / (prior.a - 1)))

First success probability 0.2
First success probability 0.14814814814814814
First success probability 0.13836477987421383
First success probability 0.11764705882352941
First success probability 0.11764705882352941
First success probability 0.11529933481152993
First success probability 0.1150278293135436
First success probability 0.10650887573964496
First success probability 0.09963547995139732
First success probability 0.09903121636167923


Average lifetime
---

In [5]:
product = pp.exponential.med(lam=3.0)

prior = pp.gamma.med(a=2.0, b=2.0)
likelihood = pp.exponential.med()

for i in range(100):
    lifetime = product.sample()
    
    prior = pp.parameter_posterior(lifetime, likelihood=likelihood, prior=prior)
    
    if i % 10 == 0:
        print("Average lifetime", prior.a / prior.b)

Average lifetime 1.4177484338327822
Average lifetime 2.318202013257616
Average lifetime 2.9794019569498493
Average lifetime 2.838969471587376
Average lifetime 2.859539970104797
Average lifetime 2.8129616152534997
Average lifetime 2.766236992862546
Average lifetime 2.911918634586746
Average lifetime 3.141641412868176
Average lifetime 3.0953963092803387
