- [fairness of coin](#Learning-fairness-of-coin)
- [Proportions of colors in deck](#Learning-Proportions-of-colors-in-deck)
- [a noisy parameter](#Learning-a-noisy-parameter)
- [First Success](#First-success)
- [Average lifetime](#Average-lifetime)

fairness of coin
---

In [6]:
import probpy as pp

coin = pp.bernoulli.med(probability=0.7)

prior = pp.beta.med(a=3.0, b=3.0) # 50 50 prior
likelihood = pp.bernoulli.med() # likelihood is a bernoulli

for _ in range(20):
    outcome = coin.sample()
    prior = pp.parameter_posterior(outcome, likelihood=likelihood, priors=prior)
    
    prediction = pp.predictive_posterior(likelihood=likelihood, priors=prior)
    
    print(prediction.probability)

0.42857142857142855
0.5
0.5555555555555556
0.5
0.5454545454545454
0.5833333333333334
0.6153846153846154
0.5714285714285714
0.5333333333333333
0.5625
0.5882352941176471
0.6111111111111112
0.631578947368421
0.65
0.6666666666666666
0.6363636363636364
0.6521739130434783
0.6666666666666666
0.68
0.6923076923076923


Proportions of colors in a deck
---

In [7]:
import numpy as np

card_probabilities = np.array([0.1, 0.2, 0.5, 0.2])

cards = pp.categorical.med(probabilities=card_probabilities)

prior = pp.dirichlet.med(alpha=np.ones(4) * 3)
likelihood = pp.categorical.med()

for i in range(200):
    card = cards.sample()    
    prior = pp.parameter_posterior(card, likelihood=likelihood, priors=prior)
        
    if i % 10 == 0:
        print(pp.mode(prior))

[0.22222222 0.33333333 0.22222222 0.22222222]
[0.21052632 0.21052632 0.26315789 0.31578947]
[0.13793103 0.13793103 0.4137931  0.31034483]
[0.15384615 0.1025641  0.46153846 0.28205128]
[0.18367347 0.12244898 0.42857143 0.26530612]
[0.15254237 0.11864407 0.47457627 0.25423729]
[0.13043478 0.14492754 0.49275362 0.23188406]
[0.11392405 0.15189873 0.46835443 0.26582278]
[0.11235955 0.14606742 0.47191011 0.26966292]
[0.11111111 0.14141414 0.47474747 0.27272727]
[0.11009174 0.1559633  0.47706422 0.25688073]
[0.11764706 0.16806723 0.4789916  0.23529412]
[0.13178295 0.1627907  0.48062016 0.2248062 ]
[0.12230216 0.16546763 0.48201439 0.23021583]
[0.12080537 0.15436242 0.48322148 0.24161074]
[0.11949686 0.1572327  0.48427673 0.23899371]
[0.1183432  0.16568047 0.46745562 0.24852071]
[0.12290503 0.16201117 0.46368715 0.25139665]
[0.12698413 0.15873016 0.47619048 0.23809524]
[0.13065327 0.16080402 0.47236181 0.2361809 ]


a noisy parameter
---

In [10]:
parameter = pp.normal.med(mu=5.0, sigma=10.0)

prior = pp.normal_inverse_gamma.med(mu=1.0, lam=5.0, a=4.0, b=3.0)
likelihood = pp.normal.med()

for i in range(100):
    sample = parameter.sample()
    
    prior = pp.parameter_posterior(sample, likelihood=likelihood, priors=prior)
    
    if i % 10 == 0:
        print("Mu estimate", prior.mu, "Sigma estimate", prior.b / (prior.a - 1))


Mu estimate 1.3537679150302209 Sigma estimate 1.3935074473064124
Mu estimate 3.3559254208507268 Sigma estimate 11.832128182351326
Mu estimate 3.4102421316098126 Sigma estimate 11.837232486579182
Mu estimate 4.119394743363548 Sigma estimate 11.90779938821417
Mu estimate 4.1388939098204105 Sigma estimate 10.66584918335366
Mu estimate 4.52814078735935 Sigma estimate 10.367748091597008
Mu estimate 4.508798756744122 Sigma estimate 10.683550166781572
Mu estimate 4.741656910057145 Sigma estimate 11.119535935098222
Mu estimate 4.840927479082687 Sigma estimate 10.46177229260767
Mu estimate 4.8143281712765145 Sigma estimate 10.179319421808534


First success
---

In [11]:
first_success = pp.geometric.med(probability=0.1)

prior = pp.beta.med(a=2.0, b=2.0)
likelihood = pp.geometric.med()

for i in range(100):
    success_on = first_success.sample()
    
    prior = pp.parameter_posterior(success_on, likelihood=likelihood, priors=prior)
    
    if i % 10 == 0:
        print("First success probability", 1 / (prior.b / (prior.a - 1)))

First success probability 0.2222222222222222
First success probability 0.10619469026548674
First success probability 0.1301775147928994
First success probability 0.11636363636363636
First success probability 0.09882352941176471
First success probability 0.09302325581395349
First success probability 0.09597523219814241
First success probability 0.10013908205841447
First success probability 0.10148514851485149
First success probability 0.1050228310502283


Average lifetime
---

In [16]:
product = pp.exponential.med(lam=3.0)

prior = pp.gamma.med(a=2.0, b=2.0)
likelihood = pp.exponential.med()

for i in range(100):
    lifetime = product.sample()
    
    prior = pp.parameter_posterior(lifetime, likelihood=likelihood, priors=prior)
    
    if i % 10 == 0:
        print("Average lifetime", prior.a / prior.b)

Average lifetime 1.4145571492678697
Average lifetime 2.190013982046198
Average lifetime 2.405062823866708
Average lifetime 2.5786006113860087
Average lifetime 2.890764323337298
Average lifetime 2.8993659973584083
Average lifetime 2.998504333618035
Average lifetime 2.9872675093627308
Average lifetime 3.0374968247769902
Average lifetime 2.9954023788069217
